name: xla-docs-build
on:
  workflow_call:
    inputs:
      dev-image:
        required: true
        type: string
        description: Base image for builds
      runner:
        required: false
        type: string
        description: Runner type for the test
        default: linux.4xlarge
jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    container:
      image: ${{ inputs.dev-image }}
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
    - name: Fetch wheels
      uses: actions/download-artifact@v4
      with:
        name: torch-xla-wheels
        path: /tmp/wheels/
    - name: Install wheels
      shell: bash
      run: |
        pip install /tmp/wheels/*.whl
    - name: Checkout PyTorch/XLA Repo
      uses: actions/checkout@v4
      with:
        path: pytorch/xla
    - name: Build docs
      shell: bash
      run: |
        cd pytorch/xla/docs
        pip install -r requirements.txt
        sphinx-build -b html source build
    - name: Checkout GitHub Pages
      uses: actions/checkout@v4
      with:
        path: gh-pages
        ref: gh-pages
    - name: Merge changes
      shell: bash
      run: |
        subdir=${{ env.BRANCH_NAME == 'master' && 'master' || format('{0}/{1}', 'release', env.BRANCH_NAME) }}
        mkdir -p gh-pages/$subdir
        cp -fR pytorch/xla/docs/build/* gh-pages/$subdir
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'gh-pages'

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    # permissions:
    #   pages: write
    #   id-token: write

    # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v4

    - name: Skip
      run: echo "testing..."
