name: xla-docs-build
on:
  workflow_call:
    inputs:
      dev-image:
        required: true
        type: string
        description: Base image for builds
      runner:
        required: false
        type: string
        description: Runner type for the test
        default: linux.4xlarge
    secrets:
      torchxla-bot-token:
        required: true
jobs:
  push-docs:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 45
    container:
      image: ${{ inputs.dev-image }}
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
    - name: Fetch wheels
      uses: actions/download-artifact@v4
      with:
        name: torch-xla-wheels
        path: /tmp/wheels/
    - name: Install wheels
      shell: bash
      run: |
        pip install /tmp/wheels/*.whl
    - name: Checkout PyTorch/XLA Repo
      uses: actions/checkout@v4
      with:
        path: pytorch/xla
    - name: Build docs
      shell: bash
      run: |
        cd pytorch/xla/docs
        pip install -r requirements.txt
        sphinx-build -b html source build
    - name: Checkout GitHub Pages
      uses: actions/checkout@v4
      with:
        path: gh-pages
        ref: gh-pages
    - name: Merge changes
      shell: bash
      run: |
        subdir=${{ env.BRANCH_NAME == 'master' && 'master' || format('{0}/{1}', 'release/', env.BRANCH_NAME) }}
        cp -fR pytorch/xla/docs/build/* gh-pages/$subdir
    - name: Show diff
      shell: bash
      run: |
        cd gh-pages
        git diff
